### ISSUE TITLE
The existence of comments will affect the analysis results

### ISSUE THREAD

**Issue by nicai4** [CoolerVoid/heap_detective#6]
as titile
<img width="820" alt="截屏2022-11-30 11 23 52" src="https://user-images.githubusercontent.com/109076057/204700175-d976de82-fb8f-43de-9a82-a5ce48199790.png">

**Comment by CoolerVoid** [comment]
Thank you very much for the advice; I can solve that issue in my spare time at the weekend.

**Comment by CoolerVoid** [comment]
Another bug "if" in the function name. I need to fix that.

**Comment by CoolerVoid** [comment]
Please test version 0.31
